name: TheEDexitVideo
favicon: null
layout_spectrum: 0.76305
typography_spectrum: 0.5515575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#D12800'
    - '#E27A51'
    - '#989C9D'
    - '#010000'
  brandStrength: 0
  lightness: 0.801826
  saturation: 0.625
  rhythmicContrast: 0.3936627
purpose: []
